### ISSUE TITLE
Building on Visual Studio

### ISSUE THREAD

**Issue by xTVaser** [DocSkellington/pcsx2-1.4.0-rr#1]
Hey, just trying to get started and I seem to be running into issues just getting it to build / run on a fresh master/movie branch.

Whenever I try to hit the "Boot from ISO" buttons I hit an access violation from one of the wxWidgets libraries.

I've installed the DirectX SDK, tried VS 2015 and 2017, and even tried installing wxWidgets locally.  I'm using the pcsx2-suite.sln file.  Was wondering if you had to set something else up that isn't mentioned in the readme or if its a problem unique to my environment that I'll have to figure out.

**Comment by xTVaser** [comment]
Got it to work by doing a "Release" build rather can a "Debug" one (although I get minor exceptions in iR5900-32.cpp which I can just ignore)

I'd be interested to see how you have been building the solution though.

**Comment by DocSkellington** [comment]
Hello,

I've never managed to get the Debug version running either (at least, not on my laptop). But as I've never needed debug info, I didn't worry too much. Maybe it will be corrected by merging with the latest PCSX2 source?

Good luck for implementing the pressure buttons. If you need help to understand something, feel free to ask. I know I haven't documented everything and some of the pocokhc's comments are in Japanese (Google Translate is our friend :p ).

**Comment by xTVaser** [comment]
I'll make a seperate issue on the pressure sensitive buttons, I've pretty much ran into a similar problem that you mentioned when we first talked. #2 

Ya I would really like to merge with the latest source, but I don't want to do a huge merge and introduce other problems until this is solved.
