### ISSUE TITLE
Pressure Sensitive Inputs seem to cause desync

### ISSUE THREAD

**Issue by xTVaser** [DocSkellington/pcsx2-1.4.0-rr#2]
I pulled in the lastest source for LilyPad which seems to have a few "input modes" as well as explicitly mentions pressure sensitivity and clearly has calculations for it. https://github.com/PCSX2/pcsx2/blob/master/plugins/LilyPad/LilyPad.cpp#L414

However I am still only getting flags of 1's and 0's for buttons pressed it seems.  I am wondering if it is because I use an Xbox360 controller (to my knowledge not pressure sensitive).  If that is the only problem then it would be nice for the TAS emulator to just use whatever the max force is, but like you mentioned, I have no idea how to find where PCSX2 uses the array buffer.  The values are thrown on it and then it throws an interrupt and the trail ends there.

I think a potential solution might be to look into the different query options for LilyPad, but if the problem lies in the controller type like I mentioned then I might try reaching out to some of the PCSX2 devs to get some information on how the emulator handles pressure sensitive inputs so the "max force" value can be thrown on the buffer instead.

**Comment by DocSkellington** [comment]
That's already a good thing done if LilyPad handles it :D.

I don't have any of my controllers with me. So, I can't test it and see if it would work with a PS3/4 controller.

Every time I try to find something in the files or online, I wonder how the team managed to build a so complex emulator without having some diagrams, global explanations, a roadmap or whatever else can be used to develop a program of this size. And if you also consider that the project is 16 years old (!), I really wonder how they've managed to update it without breaking it ^^'.

Anyway, according to [the official documentation](https://www.dropbox.com/s/onjaprt82y81sj7/EE_Users_Manual.pdf#pageContainer27) at page 55, on a PS2, it seems that the IRQ interrupt is handled by the DMA Controller. The IRQ is a "Tag". If I understand well, it may interrupt the transfer processing or setting two flags to 0 and 1. But does PCSX2 replicate the DAMC? And if yes, where and how is it implemented? I don't know (and I don't have enough free time to search in the project). So, yeah, the best solution is probably to contact the team and hope that someone is able to help you.

I'm sorry I can't help you more than that.

**Comment by xTVaser** [comment]
Good news! (i think)
I managed to log the complete output of LilyPad and it returns an additional 12 bytes, coincidentally there are 12 pressure sensitive buttons on the dualshock2.  These seem to be the pressure sensitivity bytes, 0 for unpressed and 255 for 'max force'.  I tested it out with the 360 controller's triggers and they do vary between 0-255 depending on how hard I press them! - 

![controllerb](https://user-images.githubusercontent.com/13153231/31697607-b04c407c-b386-11e7-8a49-a697ed743c9f.PNG)

So I think all that needs to be done is to store these additional bytes which at the moment appear to be [skipped](https://github.com/DocSkellington/pcsx2-1.4.0-rr/blob/master/pcsx2/TAS/KeyMovie.cpp#L64).  I'll give it a shot soon.

And ya I agree, the pcsx2 project is pretty impressive, kudos to them for keeping it going and pushing along with the lack of information.

**Comment by xTVaser** [comment]
Success! https://www.youtube.com/watch?v=e-iEL0-WeVY (before the vehicle would not even move) 

I'll work on cleaning up my changes as well as adding something to make old movie files backwards compatible.  If you would like to me to do something in particular for this let me know, right now I'm thinking the easiest thing to do is to add another conversion option like the one already in the movie menu and make these new movie files be a "version 3"

**Comment by DocSkellington** [comment]
Congratulations ! :D

If you do the conversion function from v.2 to v.3, could you also do the v.1 to v.2, please? And you can add all your modifications to v.2 (as it hasn't been officialy released yet).

To summarize what must be done for the v.1 to v.2 conversion :
- Copy the movie header
- Add the savestate header (in our case, just a bit set to 0)
- Copy every input (and change the 1 to 255 of course)

Once again, thank you for your help on the project!

**Comment by xTVaser** [comment]
Ah ok sure, that sounds a bit better.  Do you happen to have a v.1 file that i can use for testing purposes?  Otherwise I guess I can just pull down an earlier release on pocokhc's repo.

You mention a save-state header, are the movie files supposed to store a save-state at frame 0?  All along I have been manually keeping track of my own starting save-state.

**Comment by DocSkellington** [comment]
Just to answer you: the movie files do not contain a save-state at frame 0. If it becomes necessary (to assure BIOS' settings for instance), it can be easily changed.
